"""Single visual system for the FanEdge Streamlit application."""

APP_CSS = r"""
<style>
:root{
  --bg:#07100f;--bg-2:#0a1514;--surface:#101c1b;--surface-2:#142321;
  --surface-3:#1a2b28;--line:#263a36;--line-soft:rgba(160,190,181,.13);
  --text:#f5f8f4;--muted:#96aaa4;--muted-2:#6f8580;--lime:#b7f34a;
  --lime-soft:rgba(183,243,74,.10);--amber:#f3bd63;--red:#ff716d;--blue:#83b9ff;
  --radius:14px;--nav-width:220px;
}
html,.stApp{background:radial-gradient(circle at 75% -10%,#16312b 0,transparent 30rem),var(--bg);color:var(--text)}
header[data-testid="stHeader"],footer,#MainMenu{display:none}[data-testid="stToolbar"]{visibility:hidden}
.block-container{max-width:1280px;padding:0 2.5rem 6rem}
body:has(.fe-app-shell-marker) .block-container{padding-left:calc(var(--nav-width) + 3.5rem)}
h1,h2,h3,p{color:var(--text)}
.fe-wordmark{font-size:1rem;font-weight:950;letter-spacing:.13em}.fe-wordmark span{color:var(--lime)}
.fe-eyebrow{color:var(--lime);font-size:.67rem;font-weight:900;letter-spacing:.15em;text-transform:uppercase}
.fe-app-shell-marker{display:none}
.fe-topbar{position:sticky;top:0;z-index:20;height:72px;display:grid;grid-template-columns:minmax(0,1fr) auto;align-items:center;gap:1.5rem;background:rgba(7,16,15,.88);border-bottom:1px solid var(--line-soft);backdrop-filter:blur(16px)}
.fe-topbar-main{min-width:0}.fe-topbar-league{overflow:hidden;font-size:.94rem;font-weight:820;white-space:nowrap;text-overflow:ellipsis}.fe-topbar-team{margin-top:.18rem;color:var(--muted);font-size:.7rem}
.fe-topbar-week{display:flex;align-items:center;gap:.7rem}.fe-week-pill{padding:.38rem .66rem;border-radius:999px;background:var(--lime-soft);color:var(--lime);font-size:.67rem;font-weight:900;letter-spacing:.08em}.fe-profile{color:var(--muted);font-size:.72rem}
.st-key-application_nav{position:fixed;z-index:40;top:0;bottom:0;left:0;width:var(--nav-width);box-sizing:border-box;padding:1.55rem 1.2rem;background:linear-gradient(180deg,#0d1918,#091311);border-right:1px solid var(--line-soft)}
.st-key-application_nav:before{content:"FAN\00a0 EDGE";display:block;margin:.05rem .65rem 2.25rem;color:var(--text);font-size:1rem;font-weight:950;letter-spacing:.13em}
.st-key-application_nav:after{content:"AI FANTASY GM";position:absolute;left:1.85rem;bottom:1.7rem;color:var(--muted-2);font-size:.59rem;font-weight:850;letter-spacing:.14em}
.st-key-application_nav [role="radiogroup"]{gap:.35rem}.st-key-application_nav input{display:none!important}.st-key-application_nav label{padding:.72rem .72rem!important;border-radius:9px;transition:background .15s ease,color .15s ease}.st-key-application_nav label:hover{background:rgba(255,255,255,.04)}
.st-key-application_nav label:has(input:checked){background:var(--lime-soft);color:var(--lime)}
.st-key-application_nav label p{font-size:.82rem!important;font-weight:780}.st-key-application_nav [data-testid="stWidgetLabel"]{display:none}
.fe-page-head{display:flex;align-items:end;justify-content:space-between;gap:1rem;padding:2.1rem 0 1.1rem}.fe-page-head h1{margin:.38rem 0 .2rem;font-size:clamp(2.15rem,4vw,3.35rem);line-height:.96;letter-spacing:-.06em}.fe-page-head p{margin:0;color:var(--muted);font-size:.86rem;line-height:1.5}
.fe-section-title{display:flex;align-items:end;justify-content:space-between;margin:1.75rem 0 .55rem}.fe-section-title h2{margin:0;font-size:.78rem;font-weight:900;letter-spacing:.12em;text-transform:uppercase}.fe-section-title span{color:var(--muted-2);font-size:.65rem;font-weight:750}
.fe-briefing{overflow:hidden;position:relative;padding:1.4rem 0 1.2rem;border-top:1px solid var(--line-soft);border-bottom:1px solid var(--line-soft)}
.fe-briefing:after{content:"";position:absolute;right:-5rem;top:-8rem;width:17rem;height:17rem;border-radius:50%;background:rgba(183,243,74,.045)}
.fe-briefing-kicker{color:var(--muted);font-size:.72rem}.fe-briefing h2{max-width:770px;margin:.45rem 0 .35rem;font-size:clamp(1.55rem,3vw,2.25rem);letter-spacing:-.045em}.fe-briefing p{max-width:710px;margin:0;color:#bac8c4;font-size:.88rem;line-height:1.55}
.fe-action-list{border-top:1px solid var(--line-soft)}.fe-action{display:grid;grid-template-columns:40px 110px minmax(0,1fr) auto;align-items:center;gap:.85rem;min-height:76px;padding:.55rem .2rem;border-bottom:1px solid var(--line-soft)}
.fe-action-index{display:grid;place-items:center;width:28px;height:28px;border-radius:50%;background:var(--surface-2);color:var(--lime);font-size:.7rem;font-weight:900}.fe-action-kind{color:var(--muted);font-size:.64rem;font-weight:900;letter-spacing:.12em}.fe-action-copy strong{display:block;font-size:.92rem}.fe-action-copy p{margin:.22rem 0 0;color:var(--muted);font-size:.73rem}.fe-action-state{color:var(--lime);font-size:.66rem;font-weight:850}
.fe-priority{display:grid;grid-template-columns:94px minmax(0,1fr);align-items:center;gap:1.25rem;margin-top:1rem;padding:1rem 1.1rem;background:linear-gradient(120deg,var(--surface-2),rgba(16,28,27,.65));border-left:3px solid var(--lime);border-radius:0 var(--radius) var(--radius) 0}.fe-priority h3{margin:.25rem 0 .28rem;font-size:1.35rem;letter-spacing:-.035em}.fe-priority p{margin:0;color:#b9c7c3;font-size:.79rem;line-height:1.5}
.fe-edge-feed{border-top:1px solid var(--line-soft)}.fe-edge-card{display:grid;grid-template-columns:82px minmax(0,1fr) 145px;align-items:center;gap:1.15rem;padding:1rem .3rem;border-bottom:1px solid var(--line-soft);border-left:3px solid transparent}.fe-edge-card.priority-critical{border-left-color:var(--red);background:linear-gradient(90deg,rgba(255,113,109,.07),transparent 55%)}.fe-edge-card.priority-high{border-left-color:var(--lime);background:linear-gradient(90deg,rgba(183,243,74,.06),transparent 55%)}.fe-edge-meta{display:flex;align-items:center;gap:.55rem;color:var(--muted);font-size:.59rem;font-weight:900;letter-spacing:.1em}.fe-edge-meta b{color:var(--lime)}.priority-critical .fe-edge-meta b{color:var(--red)}.fe-edge-main h3{margin:.25rem 0 .12rem;font-size:1.12rem;letter-spacing:-.025em}.fe-edge-main p{margin:0;color:var(--muted);font-size:.68rem}.fe-edge-main ul{display:flex;flex-wrap:wrap;gap:.35rem .9rem;margin:.55rem 0 0;padding:0;list-style:none}.fe-edge-main li{color:#c2cfcb;font-size:.7rem}.fe-edge-main li:before{content:"•";margin-right:.35rem;color:var(--lime)}.fe-edge-action{text-align:right}.fe-edge-action span{display:block;color:var(--muted-2);font-size:.55rem;font-weight:850;letter-spacing:.08em}.fe-edge-action strong{display:block;margin-top:.28rem;color:var(--lime);font-size:.69rem;letter-spacing:.08em}.fe-edge-icon{display:grid;place-items:center;width:64px;height:64px;border-radius:50%;background:var(--lime-soft);color:var(--lime);font-weight:950}
.fe-quiet{padding:1.4rem 0;border-top:1px solid var(--line-soft);border-bottom:1px solid var(--line-soft)}.fe-quiet h3{margin:.35rem 0;font-size:1.3rem}.fe-quiet p{margin:0;color:var(--muted);font-size:.8rem}
.fe-roster-list{border-top:1px solid var(--line-soft)}
.fe-player-row{--team-color:#52606d;display:grid;grid-template-columns:52px minmax(210px,1.5fr) minmax(140px,.8fr) minmax(240px,1.15fr) auto;align-items:center;gap:.9rem;min-height:78px;padding:.5rem .65rem .5rem .25rem;border-bottom:1px solid var(--line-soft);transition:background .15s ease}.fe-player-row:hover{background:rgba(255,255,255,.025)}.fe-player-row.recommended{background:linear-gradient(90deg,rgba(183,243,74,.08),transparent 58%)}
.fe-slot{color:var(--lime);font-size:.68rem;font-weight:950;letter-spacing:.07em}.fe-player-cell{display:flex;align-items:center;gap:.78rem;min-width:0}.fe-player-identity{min-width:0}.fe-player-name{display:block;overflow:hidden;color:var(--text);font-size:.96rem;font-weight:870;letter-spacing:-.02em;white-space:nowrap;text-overflow:ellipsis}.fe-player-sub{display:flex;align-items:center;gap:.34rem;margin-top:.24rem;color:var(--muted);font-size:.68rem}.fe-matchup-cell{color:#bdcac6;font-size:.73rem}.fe-matchup-cell strong{color:var(--text);font-size:.72rem}.fe-kickoff{display:block;margin-top:.26rem;color:var(--muted-2);font-size:.63rem}.fe-signals{display:flex;align-items:center;justify-content:flex-end;gap:1.05rem}.fe-signal{text-align:right}.fe-signal strong{display:block;color:var(--text);font-size:.78rem}.fe-signal span{color:var(--muted-2);font-size:.57rem;font-weight:800;letter-spacing:.08em;text-transform:uppercase}
.fe-role-badge,.fe-status-badge,.fe-trend{display:inline-flex;align-items:center;gap:.25rem;width:max-content;border-radius:999px;font-size:.59rem;font-weight:900;letter-spacing:.06em;text-transform:uppercase}.fe-role-badge{padding:.22rem .45rem;background:var(--lime-soft);color:var(--lime)}.fe-status-badge{padding:.2rem .4rem;background:rgba(243,189,99,.11);color:var(--amber)}.fe-status-badge.out{background:rgba(255,113,109,.11);color:var(--red)}.fe-status-badge.bye{background:rgba(131,185,255,.10);color:var(--blue)}.fe-status-badge.unknown{background:rgba(150,170,164,.09);color:var(--muted)}.fe-trend.up{color:var(--lime)}.fe-trend.down{color:var(--amber)}.fe-trend.stable{color:var(--muted)}
.fe-player-visual{position:relative;display:inline-grid;flex:0 0 auto;overflow:hidden;width:50px;height:50px;border-radius:50%;background:#1a2927;border:1px solid color-mix(in srgb,var(--team-color) 60%,#fff 8%)}.fe-player-visual.compact{width:46px;height:46px}.fe-player-visual.large{width:82px;height:82px}.fe-player-image{width:100%;height:100%;object-fit:cover;display:block}.fe-player-fallback{display:none;place-items:center;width:100%;height:100%;background:linear-gradient(145deg,var(--team-color),#172521);color:#fff;text-align:center}.fe-player-fallback b{font-size:.75rem}.fe-player-fallback small{display:none}.fe-player-visual:not(:has(img)){display:grid}.fe-player-visual:not(:has(img)) .fe-player-fallback{display:grid}
.fe-team-mark{display:inline-flex;align-items:center;gap:.22rem;color:#d7e0dd;font-size:.63rem;font-weight:850}.fe-team-mark img{width:17px;height:17px;object-fit:contain}.fe-team-mark.unknown{color:var(--muted)}
.fe-empty-row{padding:1.1rem .8rem;border-bottom:1px solid var(--line-soft);color:var(--muted);font-size:.75rem}
.fe-swap{display:grid;grid-template-columns:minmax(0,1fr) 38px minmax(0,1fr);align-items:center;gap:.8rem;margin:.7rem 0 1rem;padding:1rem;background:linear-gradient(120deg,var(--surface-2),var(--surface));border:1px solid rgba(183,243,74,.2);border-radius:var(--radius)}.fe-swap-side{display:flex;align-items:center;gap:.65rem}.fe-swap-side.right{justify-content:flex-end;text-align:right}.fe-swap-arrow{color:var(--lime);font-size:1.25rem;text-align:center}.fe-swap-label{color:var(--muted-2);font-size:.58rem;font-weight:900;letter-spacing:.1em}.fe-swap-name{margin:.16rem 0;font-size:.85rem;font-weight:850}.fe-confidence{color:var(--lime);font-size:.61rem;font-weight:900;letter-spacing:.08em}
.fe-waiver-list{border-top:1px solid var(--line-soft)}.fe-waiver-row{display:grid;grid-template-columns:35px minmax(210px,1.4fr) minmax(135px,.75fr) minmax(210px,1fr);align-items:center;gap:.9rem;min-height:78px;padding:.5rem .35rem;border-bottom:1px solid var(--line-soft)}.fe-rank{color:var(--muted-2);font-size:.72rem;font-weight:900}.fe-fit{color:#bfcbc8;font-size:.7rem;line-height:1.45}.fe-fit strong{display:block;color:var(--text);font-size:.72rem}.fe-watchlist .fe-waiver-row{min-height:68px;opacity:.9}
.fe-ai-hero{display:grid;grid-template-columns:minmax(0,1.35fr) minmax(260px,.65fr);gap:2rem;align-items:end;padding:2.2rem 0 1.5rem;border-bottom:1px solid var(--line-soft)}.fe-ai-hero h1{max-width:680px;margin:.5rem 0 .65rem;font-size:clamp(2.4rem,5vw,4.2rem);line-height:.95;letter-spacing:-.065em}.fe-ai-hero p{max-width:630px;margin:0;color:#b6c5c0;font-size:.9rem;line-height:1.6}.fe-capability{padding:1rem;border-left:2px solid var(--lime);background:var(--lime-soft);color:#c8d4d0;font-size:.75rem;line-height:1.55}.fe-prompt-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:.65rem;margin:1rem 0}.fe-prompt{padding:.9rem;background:var(--surface);border:1px solid var(--line-soft);border-radius:10px;color:#cad5d1;font-size:.74rem;line-height:1.45}
.fe-ai-result{margin-top:1rem;padding:1.1rem 1.2rem;background:var(--surface-2);border-left:3px solid var(--lime);border-radius:0 var(--radius) var(--radius) 0}.fe-ai-result h3{margin:.2rem 0 .4rem;font-size:.9rem}.fe-ai-result p{margin:0;color:#c3cfcb;font-size:.8rem;line-height:1.6}
.fe-landing-nav{height:72px;display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid var(--line-soft)}.fe-landing-meta{color:var(--muted);font-size:.67rem;font-weight:800;letter-spacing:.1em}.fe-landing{display:grid;grid-template-columns:minmax(0,1.1fr) minmax(350px,.9fr);gap:4rem;align-items:center;min-height:calc(100vh - 140px)}.fe-landing h1{margin:.8rem 0 1rem;font-size:clamp(3.7rem,7vw,6.3rem);line-height:.86;letter-spacing:-.075em}.fe-landing h1 span{color:var(--lime)}.fe-landing-copy>p{max-width:570px;margin:0;color:#afc0ba;font-size:1rem;line-height:1.7}.fe-connect{padding:1.35rem;background:linear-gradient(145deg,var(--surface-2),var(--surface));border:1px solid var(--line);border-radius:var(--radius)}.fe-connect h2{margin:.35rem 0 .3rem;font-size:1.35rem}.fe-connect p{margin:0 0 .65rem;color:var(--muted);font-size:.77rem}.fe-trust{text-align:center;color:var(--muted-2);font-size:.66rem}
.stTextInput input,.stSelectbox [data-baseweb="select"]>div{background:var(--surface)!important;border-color:var(--line)!important;border-radius:9px!important;color:var(--text)!important}.stTextInput input:focus{border-color:var(--lime)!important;box-shadow:0 0 0 2px var(--lime-soft)!important}
.stButton button,.stFormSubmitButton button{min-height:44px;border-radius:9px;font-weight:850;transition:transform .14s ease,filter .14s ease}.stButton button[kind="primary"],.stFormSubmitButton button[kind="primary"]{background:var(--lime);border-color:var(--lime);color:#07100b}.stButton button:hover,.stFormSubmitButton button:hover{transform:translateY(-1px);filter:brightness(1.04)}
[data-testid="stExpander"]{background:rgba(16,28,27,.6);border-color:var(--line-soft)!important;border-radius:10px!important}[data-testid="stAlert"]{border-radius:10px}.stSelectbox{max-width:420px}
@media(max-width:900px){
  :root{--nav-width:0px}.block-container,body:has(.fe-app-shell-marker) .block-container{padding:0 1rem 7rem}
  .st-key-application_nav{top:auto;bottom:0;width:100%;height:68px;padding:.38rem .55rem;background:rgba(9,19,17,.96);border-top:1px solid var(--line);border-right:0;backdrop-filter:blur(16px)}
  .st-key-application_nav:before,.st-key-application_nav:after{display:none}.st-key-application_nav [role="radiogroup"]{display:grid;grid-template-columns:repeat(4,1fr);gap:.15rem}.st-key-application_nav label{justify-content:center!important;padding:.65rem .15rem!important;text-align:center}.st-key-application_nav label p{font-size:.68rem!important}
  .fe-topbar{height:62px}.fe-profile{display:none}.fe-page-head{padding-top:1.5rem}.fe-player-row{grid-template-columns:38px minmax(180px,1fr) minmax(150px,.85fr) auto}.fe-player-row>.fe-matchup-cell{display:none}.fe-signals{gap:.65rem}.fe-waiver-row{grid-template-columns:28px minmax(190px,1.2fr) minmax(130px,.8fr) minmax(150px,.9fr)}.fe-waiver-row>.fe-matchup-cell{display:none}.fe-edge-card{grid-template-columns:70px minmax(0,1fr) 120px}.fe-ai-hero{grid-template-columns:1fr}.fe-prompt-grid{grid-template-columns:1fr}
}
@media(max-width:620px){
  .fe-topbar{gap:.7rem}.fe-topbar-week{gap:.3rem}.fe-week-pill{padding:.3rem .45rem}.fe-topbar-league{font-size:.82rem}.fe-topbar-team{font-size:.62rem}.fe-page-head{display:block}.fe-page-head h1{font-size:2.35rem}
  .fe-action{grid-template-columns:32px minmax(0,1fr) auto;gap:.6rem;min-height:72px}.fe-action-kind{display:none}.fe-action-copy p{padding-right:.25rem}.fe-action-state{font-size:.58rem}
  .fe-priority{grid-template-columns:72px minmax(0,1fr);gap:.8rem;padding:.85rem}.fe-player-visual.large{width:68px;height:68px}
  .fe-player-row{grid-template-columns:32px minmax(0,1fr) auto;gap:.55rem;padding:.5rem .1rem;min-height:72px}.fe-player-row>.fe-matchup-cell,.fe-player-row>.fe-role-column{display:none}.fe-player-name{font-size:.88rem}.fe-player-visual{width:44px;height:44px}.fe-signals{gap:.5rem}.fe-signal:nth-child(n+3){display:none}.fe-signal strong{font-size:.7rem}.fe-signal span{font-size:.52rem}
  .fe-swap{grid-template-columns:1fr 26px 1fr;padding:.8rem .6rem}.fe-swap-side{display:block}.fe-swap-side.right{display:block}.fe-swap-side .fe-player-visual{margin-bottom:.35rem}.fe-swap-name{font-size:.72rem}
  .fe-waiver-row{grid-template-columns:24px minmax(0,1fr) auto;gap:.55rem;padding:.55rem .1rem}.fe-waiver-row>.fe-fit,.fe-waiver-row>.fe-matchup-cell{display:none}.fe-waiver-row>.fe-signals .fe-signal:nth-child(n+3){display:none}.fe-edge-card{grid-template-columns:58px minmax(0,1fr);gap:.7rem;padding:.85rem .1rem}.fe-edge-card .fe-player-visual.large{width:54px;height:54px}.fe-edge-action{grid-column:2;text-align:left}.fe-edge-main ul{display:block}.fe-edge-main li{margin-top:.28rem}.fe-landing{grid-template-columns:1fr;gap:2rem;align-content:center;min-height:auto;padding:3rem 0}.fe-landing h1{font-size:clamp(3.5rem,18vw,5rem)}
}
</style>
"""
